### ISSUE TITLE
run_issue

### ISSUE THREAD

**Issue by JoseLopezArcondo** [johnomics/tapestry#9]
Hello, 
I installed tapestry with "conda install -c bioconda tapestry"
I found this error when trying to run "weave -h". 

jose@mutant11:[SCREEN]:/linuxhome/tmp/jose:weave -h
Traceback (most recent call last):
  File "/home/jose/miniconda3/bin/weave", line 4, in <module>
    __import__('pkg_resources').run_script('tapestry==1.0.0', 'weave')
  File "/home/jose/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jose/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/weave' not found in metadata at '/home/jose/miniconda3/lib/python3.8/site-packages/tapestry-1.0.0-py3.8.egg-info'

**Comment by johnomics** [comment]
Hello Jose, thank you for trying Tapestry. I'm sorry you're having installation issues. I'm afraid I am no longer working on Tapestry or using python, conda or bioconda. When I just tried a fresh install of conda and Tapestry, I was unable to complete the installation myself; there are incompatible specifications but conda does not report what they are. I have been unable to resolve the problem.

Are you able to install and use other bioconda packages successfully? Did you receive any errors when installing Tapestry with conda? If so, and you are still interested in using the tool, please could you post them here?

**Comment by johnomics** [comment]
I assume this is way too late, but I've made some compatibility updates to Tapestry, if you're still interested in trying it please try again with version 1.0.1. Closing this issue for now.
